import React from "react";
import { GoogleColor, COLOR_HEX } from "./content";
import { Button } from "./ui/Button";
import { BadgeIcon } from "./BadgeIcon";

// --- CONSTANTS ---

const POSTER_GRADIENTS: Record<GoogleColor, string> = {
  yellow:
    "linear-gradient(180deg, #FBD79B -3.84%, #F7CE00 25.11%, #EBA400 52.07%, #F13E00 97.52%)",
  red: "linear-gradient(180deg, #F8B4B4 -3.84%, #EA4335 25.11%, #C5221F 52.07%, #800000 97.52%)",
  blue: "linear-gradient(180deg, #AECBFA -3.84%, #4285F4 25.11%, #1967D2 52.07%, #174EA6 97.52%)",
  green:
    "linear-gradient(180deg, #A8DAB5 -3.84%, #34A853 25.11%, #1E8E3E 52.07%, #0D652D 97.52%)",
};

// NEW: We map to background colors instead of border colors for the clip-path border trick
const POSTER_BG_COLORS: Record<GoogleColor, string> = {
  yellow: "bg-[#FFDF20]",
  red: "bg-[#FF5050]",
  blue: "bg-[#5B9BFF]",
  green: "bg-[#4FE073]",
};

// Extracted Base64 strings for DRY component rendering
const ALIEN_BASE64_DATA = [
  "iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAYAAAAMzckjAAALaElEQVR4nO3dvWmbaxiAYemgJgsYD5EFhEADuDWETOEJXLpKmSmCwV3IAAIh0h2Ch/AGKXWqcAIBk5/XeWXf1zXAw6Pk86ebp9FiAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAc7OcvQBwOrab9XH2Djyd3f7gnQ8sFovF4p/ZCwAA8HcJQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADHL2QvASNvN+jh7h8dcffg0e4VH3d5/nb0CT+jN61ezV3jU+7cXs1d41G5/8J3Ji+ECCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAEDMcvYCtG036+PIeVcfPo0cN9zt/dfZK8DJevP61ewVHvX+7cXQebv9wXcw07gAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABCznL0Az8t2sz6OnHf14dPIcYvb+69D5wF88+b1q6Hz3r+9GDpvtz/4TuenuQACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDErGYvAPzo4eZy9gqPOr++m70C3/G8AL/KBRAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACDGL4Ew1e3919krAPwU7yteEhdAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGL8EAvyyh5vLofPOr++Gzjt1o//9AH6VCyAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQs5q9APCj8+u7ofMebi6HzuNlG/38AafHBRAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAmNXsBYCnd359N3sFvuP/A5jNBRAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBmOXsB2rab9XHkPL+wADyVh5vLofN2+4PvYKZxAQQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgZjl7AZ6X7WZ9HDnv/Ppu5LjFw83l0Hmjjf688JLU/n5Hf97d/uA7nZ/mAggAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAzGr2AnDKzq/vhs57uLkcOm+00Z+X01J7/k7988JMLoAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxKxmLwD8vvPru6HzHm4uh87jtHhegG9cAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIWc1egLbd/rCcvcNjtot3x9k7QMXZv++Gzjv19wvM5AIIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQMxy9gLA79tu1seR83b7g3fCC+Z5Ab5xAQQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABO3H/i0o/DFoMwHgAAAABJRU5ErkJggg==",
  "iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAYAAAAMzckjAAAKuElEQVR4nO3dQYpaWRSA4bJJxg0qJFsRwezA1fQyejXuIIK4lQS0IOOCtmc9S5Gkb+pa9X/fAg7n+eS9nzt5Dw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDyL2QvAPdttN7fZOwC/5ng6e8fBd/wxewEAAF6WAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADGL2QvASLvt5jZy3uePH0aOA17Qpy9fh847ns7embwZTgABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiFnMXoC23XZzGznv88cPI8c9fHt6GjoPeDl/vn8/dN6nL1+Hzjuezt7BTOMEEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYt7NXgD4dfvr4+wVnnVYLWevkOB/APwsJ4AAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxvgTCT9ltN7eR8z5//DBy3MO3p6eh84DXa/TzYPTz6tPg5+nxdF6MnMfb5gQQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgxpdAgN9mf30cOu+wWg6dN8vo3wXgZzkBBACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiPElEKb69vQ0ewWAH+J5xVviBBAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACDGl0DgFTuslkPn7a+PQ+fxOo3+XwH3xwkgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADHvZi8A3I/Dajl7hQS/MzCbE0AAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYhazF6Btt93cRs47rJYjxwH8Z399HDrveDp7BzONE0AAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYhazF6B12W03t5HzDqvlyHHDHS+X2Ss8a7dez17hRbkf98X9+H/218eh846ns3c6P8wJIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxi9kL8HvttpvbyHmH1XLkuOGOl8vQebv1eui80e79eu99v9Hu/Xrvfb/Rate7vz4OnXc8nTXCG+YEEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAICYxewFeF12281t5Ly/bv+MHPewW6+HzjteLkPnjTb6eu+d+3Ffavdj9PX+vRh7BnM8nb3T+WFOAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIWcxegLbddnObvcNzDqvl7BWedbxchs7brddD5937fqPd+/Xe+36j7a+Ps1d41vF09g5mGieAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQsZi8A92y33dxm7/Ccw2o5e4UXtb8+zl7hWe7HfTmezt5x8B1OAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIWcxeAPh1u+3mNnuHl3Q8ne/6meV+AK+FE0AAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAV+VfQkijI+5gdFYAAAAASUVORK5CYII=",
  "iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAYAAAAMzckjAAALwElEQVR4nO3dMW4bWRZA0eKAgTMBTpz1PggCFXglWoMXMmvQShwUQHAfyiYRoEwZO2tMYqHd/aVP8p6zgIdHifV58ZNaFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4TLvZC9C2Hg+X2Tu8ZzudPSNwo5wv8Gv/mb0AAACfSwACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAICY/ewFuC3r8XAZOW97fBg5blm+fhk6bl0Gf97TeTdyHtyT4efLj28jxy3Ly9vQcc4XZnIDCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAEDMfvYCxD2/zt7gXduPb0PnrcvhMnQg3JHRz9vy8jZ23pWfV/A73AACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAELObvQBt6/FwGTlv+z5y2rIsfzyMnff1y9h5cE9e3sbOe34dOm79OXTcsp3OfoOZxg0gAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADG72QvASOvxcBk5b3t8GDkO+ETr0+vQedvp7DeTu+EGEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIGY/ewHaRr+5A+CjDH/TkDeLMJEbQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBidrMX4Lasx8Nl5Lzt8WHkOICbsT69Dp23nc5+0/nb3AACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDE7GcvAPxzo98kMJo3vfw7/r/AR3EDCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAEDMfvYCwP1an16HztseH4bOG2305wX4KG4AAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgZj97AeCf2x4fhs5bn16HzuO6jP6+ALfLDSAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMfvZCwDXY3t8mL3CTfP3A26FG0AAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIjZzV6Aj7UeD5eR87Yf30aOW5aXt7HzAG7F1y9Dx63//d/QedvprBHumBtAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGL2sxfgxry8zd7gXevT69B52+PD0HnL89j94K78MfZ5u/rz4MrPU+6bG0AAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYvazF+DGPL/O3oD/s/6cvQFl2/fZG3wy5x93xA0gAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADH72QvwsbbTeTdy3rocLiPncV1Gf1+4LuvR8/tvrD9nb/A+zy+/ww0gAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADH72QtwW7bTeTd7h/esx8Nl9g7Afbr28w9+hxtAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGG8CYSpv7gBuxejzyptFmMkNIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAx+9kLcFvW4+Eyct72+DByHMBfrv18WZfB5+npvBs5j/vmBhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAmP3sBYh7fp29wadaf46dt53Ou7ETuWejvy/rcriMnLd9b50HMJMbQACAGAEIABAjAAEAYgQgAECMAAQAiBGAAAAxAhAAIEYAAgDECEAAgBgBCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBidrMXoG09Hi6zd/hM2+nsmYNfcB7A53EDCAAQIwABAGIEIABAjAAEAIgRgAAAMQIQACBGAAIAxAhAAIAYAQgAECMAAQBiBCAAQIwABACIEYAAADECEAAgRgACAMQIQACAGAEIABAjAAEAYgQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAL/wJqD2faN1P7HUAAAAASUVORK5CYII=",
];

// --- HELPER COMPONENTS ---

// NEW: DRY Component abstraction for your SVG repeating pattern
function AlienIcon({ id, base64 }: { id: string; base64: string }) {
  return (
    <svg
      width="45"
      height="45"
      viewBox="0 0 45 45"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <rect width="45" height="45" fill={`url(#pattern_${id})`} />
      <defs>
        <pattern
          id={`pattern_${id}`}
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        >
          <use xlinkHref={`#image_${id}`} transform="scale(0.0015625)" />
        </pattern>
        <image
          id={`image_${id}`}
          width="640"
          height="640"
          preserveAspectRatio="none"
          xlinkHref={`data:image/png;base64,${base64}`}
        />
      </defs>
    </svg>
  );
}

// --- MAIN COMPONENT ---

export interface ArticlePosterProps {
  title: string;
  tag: string;
  desc: string;
  color: GoogleColor;
  buttonText?: string;
}

export function ArticlePoster({
  title,
  tag,
  desc,
  color,
  buttonText = "Read the Full post →",
}: ArticlePosterProps) {
  const glowColor = COLOR_HEX[color];

  return (
    <article
      className="relative flex w-full flex-col items-center justify-center gap-8 overflow-hidden p-6 md:gap-9.25 md:p-10"
      style={{
        background: `linear-gradient(180deg, ${glowColor}E6 0%, rgba(22, 36, 86, 0) 86.06%)`,
      }}
    >
      {/* Poster Image Container */}
      <div
        className="relative flex w-full max-w-162 flex-none aspect-648/614 items-center justify-center rounded-lg p-4 shadow-[0px_4px_4px_rgba(0,0,0,0.25)] md:p-6 lg:p-3"
        style={{ background: POSTER_GRADIENTS[color] }}
      >
        {/* DOT PATTERN OVERLAY */}
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(#00000025_1px,transparent_1px)] bg-[size:6px_6px]" />

        <div className="relative z-10 flex h-full w-full flex-col items-center justify-center drop-shadow-[0px_-6px_3px_rgba(0,0,0,0.15)]">
          <div
            className={`absolute inset-0 ${POSTER_BG_COLORS[color]} [clip-path:polygon(32px_0,calc(100%-32px)_0,100%_32px,100%_100%,0_100%,0_32px)]`}
          />

          <div className="absolute inset-[6px] bg-navy-900 [clip-path:polygon(28px_0,calc(100%-28px)_0,100%_28px,100%_100%,0_100%,0_28px)] md:inset-[8px]" />

          <div className="relative z-10 flex h-full w-full flex-col items-center justify-center pb-4 pt-8">
            <div className="absolute -top-10 left-1/2 w-45 -translate-x-1/2 md:-top-22 md:w-60 lg:w-78.75">
              <BadgeIcon
                color={color}
                className="h-auto w-full drop-shadow-lg"
              />
            </div>

            <span className="mt-8 px-4 text-center font-pixel text-xl text-white drop-shadow-[4px_4px_0_#050a1f] md:text-3xl lg:text-4xl">
              {tag}
            </span>
          </div>
        </div>
      </div>

      {/* Content Container */}
      <div className="flex w-full max-w-162 flex-col items-start gap-4 md:gap-6">
        {/* DRY Alien Icons Mockup */}
        <div className="flex flex-row items-start">
          {ALIEN_BASE64_DATA.map((base64, index) => (
            <AlienIcon key={index} id={`alien_${index}`} base64={base64} />
          ))}
        </div>

        <h3 className="font-pixel text-md leading-[1.3] text-[#FAFAFA] md:text-md">
          {title}
        </h3>

        <p className="font-sans text-justify text-xs leading-relaxed text-[#FAFAFA] md:text-xs">
          {desc}
        </p>

        <Button className="mt-2 bg-[#F0B100] text-[#432004]! text-[10px]! md:text-xs! leading-[1.4] md:px-5! md:py-2.5! border-none! shadow-[inset_4px_4px_0px_#FFF085,inset_-4px_-4px_0px_#D08700,3px_3px_0px_#432004]! transition-transform hover:scale-105">
          {buttonText}
        </Button>
      </div>
    </article>
  );
}
